////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 14.2
//  \   \         Application : xaw2verilog
//  /   /         Filename : clockDiv.v
// /___/   /\     Timestamp : 10/30/2014 16:47:12
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -st /afs/ece.cmu.edu/usr/chuehsig/Private/18545/TestCart/Cores/./clockDiv.xaw /afs/ece.cmu.edu/usr/chuehsig/Private/18545/TestCart/Cores/./clockDiv
//Design Name: clockDiv
//Device: xc5vlx110t-3ff1136
//
// Module clockDiv
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUTDCM0 = 0.212 ns
`timescale 1ns / 1ps

module clockDiv(CLKIN1_IN, 
                RST_IN, 
                CLK0_OUT,CLK2X_OUT, 
                LOCKED_OUT);

    input CLKIN1_IN;
    input RST_IN;
   output CLK0_OUT,CLK2X_OUT;
   output LOCKED_OUT;
   
   wire CLKFBDCM_CLKFBIN;
   wire CLKFB_IN;
   wire CLKIN1_IBUFG;
   wire CLKOUTDCM0_CLKIN;
   wire CLK0_BUF,CLK2X_BUF;
   wire GND_BIT;
   wire [4:0] GND_BUS_5;
   wire [6:0] GND_BUS_7;
   wire [15:0] GND_BUS_16;
   wire OR2_OUT;
   wire PLL_ADV_LOCKED_INV;
   wire PLL_ADV_LOCKED_OUT;
   wire SRL16_Q_OUT;
   wire VCC_BIT;
   
   assign GND_BIT = 0;
   assign GND_BUS_5 = 5'b00000;
   assign GND_BUS_7 = 7'b0000000;
   assign GND_BUS_16 = 16'b0000000000000000;
   assign VCC_BIT = 1;
   assign CLK0_OUT = CLKFB_IN;
   BUFG  CLKIN1_IBUFG_INST (.I(CLKIN1_IN), 
                            .O(CLKIN1_IBUFG));
   BUFG  CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));

   BUFG  CLK2X_BUFG_INST (.I(CLK2X_BUF), 
                        .O(CLK2X_OUT));


   DCM_ADV #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(1), 
         .CLKFX_MULTIPLY(4), .CLKIN_DIVIDE_BY_2("FALSE"), 
         .CLKIN_PERIOD(17.361), .CLKOUT_PHASE_SHIFT("NONE"), 
         .DCM_AUTOCALIBRATION("TRUE"), .DCM_PERFORMANCE_MODE("MAX_SPEED"), 
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"), 
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"), 
         .FACTORY_JF(16'hF0F0), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE"), 
         .SIM_DEVICE("VIRTEX5") ) DCM_ADV_INST (.CLKFB(CLKFB_IN), 
                         .CLKIN(CLKOUTDCM0_CLKIN), 
                         .DADDR(GND_BUS_7[6:0]), 
                         .DCLK(GND_BIT), 
                         .DEN(GND_BIT), 
                         .DI(GND_BUS_16[15:0]), 
                         .DWE(GND_BIT), 
                         .PSCLK(GND_BIT), 
                         .PSEN(GND_BIT), 
                         .PSINCDEC(GND_BIT), 
                         .RST(OR2_OUT), 
                         .CLKDV(), 
                         .CLKFX(), 
                         .CLKFX180(), 
                         .CLK0(CLK0_BUF), 
                         .CLK2X(CLK2X_BUF), 
                         .CLK2X180(), 
                         .CLK90(), 
                         .CLK180(), 
                         .CLK270(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(LOCKED_OUT), 
                         .PSDONE());
   INV  INV_INST (.I(PLL_ADV_LOCKED_OUT), 
                 .O(PLL_ADV_LOCKED_INV));
   OR2  OR2_INST (.I0(SRL16_Q_OUT), 
                 .I1(RST_IN), 
                 .O(OR2_OUT));
   PLL_ADV #( .BANDWIDTH("OPTIMIZED"), .CLKIN1_PERIOD(37.037), 
         .CLKIN2_PERIOD(37.037), .CLKOUT0_DIVIDE(15), .CLKOUT0_PHASE(0.000), 
         .CLKOUT0_DUTY_CYCLE(0.500), .COMPENSATION("PLL2DCM"), 
         .DIVCLK_DIVIDE(1), .CLKFBOUT_MULT(32), .CLKFBOUT_PHASE(0.0), 
         .REF_JITTER(0.005000) ) PLL_ADV_INST (.CLKFBIN(CLKFBDCM_CLKFBIN), 
                         .CLKINSEL(1'b1), 
                         .CLKIN1(CLKIN1_IBUFG), 
                         .CLKIN2(), 
                         .DADDR(GND_BUS_5[4:0]), 
                         .DCLK(GND_BIT), 
                         .DEN(GND_BIT), 
                         .DI(GND_BUS_16[15:0]), 
                         .DWE(GND_BIT), 
                         .REL(GND_BIT), 
                         .RST(RST_IN), 
                         .CLKFBDCM(CLKFBDCM_CLKFBIN), 
                         .CLKFBOUT(), 
                         .CLKOUTDCM0(CLKOUTDCM0_CLKIN), 
                         .CLKOUTDCM1(), 
                         .CLKOUTDCM2(), 
                         .CLKOUTDCM3(), 
                         .CLKOUTDCM4(), 
                         .CLKOUTDCM5(), 
                         .CLKOUT0(), 
                         .CLKOUT1(), 
                         .CLKOUT2(), 
                         .CLKOUT3(), 
                         .CLKOUT4(), 
                         .CLKOUT5(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(PLL_ADV_LOCKED_OUT));
   SRL16  SRL16_INST (.A0(GND_BIT), 
                     .A1(GND_BIT), 
                     .A2(GND_BIT), 
                     .A3(GND_BIT), 
                     .CLK(CLKIN1_IBUFG), 
                     .D(PLL_ADV_LOCKED_INV), 
                     .Q(SRL16_Q_OUT));
endmodule
